# start : docker-compose up -d --build
# stop : docker-compose down
version: '4' 
services:

  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - node-server

  node-server: 
    build: . 
    ports:
      - "3001:3001" 
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./routes:/usr/src/app/router
      - ./controller:/usr/src/app/controller
      - ./middleware:/usr/src/app/middleware
      - ./database.js:/usr/src/app/database.js
      - ./courses:/usr/src/app/courses
      - ./users:/usr/src/app/users
    env_file:
      - .env
      
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: SAT 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db # DB host
      PMA_PORT: 3306 # DB port
      PMA_USER: root # DB user
      PMA_PASSWORD: root # DB password
    ports:
      - "8081:80"
    depends_on:
      - db

  linux-terminal-user1:
    build:
      context: ./terminals
      dockerfile: Dockerfile
    container_name: linux-terminal-user1
    ports:
      - "4001:4001"
    environment:
      - TTYD_PORT=4001
    tty: true
    stdin_open: true
    volumes:
      - ./lab-session-data/user1:/usr/src/app:rw
    working_dir: /usr/src/app

  linux-terminal-user2:
    build:
      context: ./terminals
      dockerfile: Dockerfile
      args:
        TTYD_PORT: 4002
    container_name: linux-terminal-user2
    ports:
      - "4002:4002"
    environment:
      - TTYD_PORT=4002
    tty: true
    stdin_open: true
    volumes:
      - ./lab-session-data/user2:/usr/src/app/lab:rw
    working_dir: /usr/src/app

  linux-terminal-user3:
    build:
      context: ./terminals
      dockerfile: Dockerfile
      args:
        TTYD_PORT: 4003
    container_name: linux-terminal-user3
    ports:
      - "4003:4003"
    environment:
      - TTYD_PORT=4003
    tty: true
    stdin_open: true
    volumes:
      - ./lab-session-data/user3:/usr/src/app:rw
    working_dir: /usr/src/app

  linux-terminal-user4:
    build:
      context: ./terminals
      dockerfile: Dockerfile
      args:
        TTYD_PORT: 4004
    container_name: linux-terminal-user4
    ports:
      - "4004:4004"
    environment:
      - TTYD_PORT=4004
    tty: true
    stdin_open: true
    volumes:
      - ./lab-session-data/user4:/usr/src/app:rw
    working_dir: /usr/src/app

volumes:
  mysql_data_test: 
    driver: local
