# start : docker-compose up -d --build
# stop : docker-compose down
# tar build : tar -cvf SAT_services.tar controller courses frontend middleware routes .env database.js docker-compose.yml Dockerfile index.js package-lock.json package.json wait-for-it.sh
# tar extained: tar -xvf SAT_services.tar   
version: '4' 
services:

  # react-frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3003:80"
  #   depends_on:
  #     - node-server

  node-server: 
    build: . 
    ports:
      - "3002:3002" 
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./routes:/usr/src/app/routes
      - ./controller:/usr/src/app/controller
      - ./middleware:/usr/src/app/middleware
      - ./database.js:/usr/src/app/database.js
      - ./courses:/usr/src/app/courses
      - ./users:/usr/src/app/users
      - ./lab-session-data:/usr/src/app/lab-session-data
    env_file:
      - .env
      
  db:
    image: mysql:9.4
    environment:
      MYSQL_ROOT_PASSWORD: password_1234
      MYSQL_DATABASE: SAT 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.2
    container_name: phpmyadmin
    environment:
      PMA_HOST: db # DB host
      PMA_PORT: 3306 # DB port
    ports:
      - "8081:80"
    depends_on:
      - db

  # linux-terminal-user1:
  #   build:
  #     context: ./terminals
  #     dockerfile: Dockerfile
  #   container_name: linux-terminal-user1
  #   ports:
  #     - "4001:4001"
  #   environment:
  #     - TTYD_PORT=4001
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - user1_data:/usr/src/app:rw
  #   tmpfs:
  #     - /tmp
  #   working_dir: /usr/src/app
  #   user: 1000:1000
  #   mem_limit: 512m
  #   cpus: 0.25

  # linux-terminal-user2:
  #   build:
  #     context: ./terminals
  #     dockerfile: Dockerfile
  #     args:
  #       TTYD_PORT: 4002
  #   container_name: linux-terminal-user2
  #   ports:
  #     - "4002:4002"
  #   environment:
  #     - TTYD_PORT=4002
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - user2_data:/usr/src/app:rw
  #   tmpfs:
  #     - /tmp
  #   working_dir: /usr/src/app
  #   user: 1000:1000
  #   mem_limit: 512m
  #   cpus: 0.25

  # linux-terminal-user3:
  #   build:
  #     context: ./terminals
  #     dockerfile: Dockerfile
  #     args:
  #       TTYD_PORT: 4003
  #   container_name: linux-terminal-user3
  #   ports:
  #     - "4003:4003"
  #   environment:
  #     - TTYD_PORT=4003
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - user3_data:/usr/src/app:rw
  #   tmpfs:
  #     - /tmp
  #   working_dir: /usr/src/app
  #   user: 1000:1000
  #   mem_limit: 512m
  #   cpus: 0.25

  # linux-terminal-user4:
  #   build:
  #     context: ./terminals
  #     dockerfile: Dockerfile
  #     args:
  #       TTYD_PORT: 4004
  #   container_name: linux-terminal-user4
  #   ports:
  #     - "4004:4004"
  #   environment:
  #     - TTYD_PORT=4004
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - user4_data:/usr/src/app:rw
  #   tmpfs:
  #     - /tmp
  #   working_dir: /usr/src/app
  #   user: 1000:1000
  #   mem_limit: 512m
  #   cpus: 0.25

volumes:
  mysql_data_test: 
    driver: local
  # user1_data:
  #   driver: local
  # user2_data:
  #   driver: local
  # user3_data:
  #   driver: local
  # user4_data:
  #   driver: local