# start : docker-compose up -d --build
# stop : docker-compose down
version: '3' 
services:
  node-server: 
    build: . 
    ports:
      - "3001:3001" 
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./lab:/usr/src/lab
      
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root 
      MYSQL_DATABASE: SAT 
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data_test:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: db # DB host
      PMA_PORT: 3306 # DB port
      PMA_USER: root # DB user
      PMA_PASSWORD: root # DB password
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  mysql_data_test: 
    driver: local
